#!/usr/bin/php
<?php

// include the common PHP code file
require("a2.php");

$usage = "Usage: $argv[0] Name Num1 Num2";
// Init connection with database
//$db = dbConnect(DB_CONNECTION);

// Check arguments
if (count($argv) < 3) exit("$usage\n");

$name = $argv[1];
$num1 = $argv[2];
$num2 = $argv[3];

"with recursive Tree(Actor, Degree) as (
    select (539) as Actor, 0 as Degree -- pass in starting actor id and 0 as the default degree
union all
    select distinct A.actor_id, (T.Degree + 1) as Degree from Acting as A, Tree as T
    where A.actor_id not in (Actor)
    and A.movie_id in (select distinct movie_id from Acting where actor_id in (Actor))
    and T.Degree < 1 -- six degrees for now
)
select T.Actor, T.Degree, A.name from Tree as T, Actor as A
where T.Actor = A.id";

$degreeOne = "select actor_id, 1 as Degree from acting 
    where actor_id != 593 and movie_id in 
    (select movie_id from acting where actor_id = 100593)";

$degreeTwo = "with One as (select actor_id, 1 as Degree from acting 
        where actor_id != 100 and movie_id in 
        (select movie_id from acting where actor_id = 100))
    select A.actor_id, 2 as Degree from Acting as A 
    where actor_id not in (select actor_id from One) 
    and movie_id in (select movie_id from acting where actor_id in (select actor_id from One)"
// Get all connections between 
?>
