#!/usr/bin/php
<?php

// include the common PHP code file
require("a2.php");

$usage = "Usage: $argv[0] Name Num1 Num2";
// Init connection with database
$db = dbConnect(DB_CONNECTION);

// Check arguments
if (count($argv) < 3) exit("$usage\n");

$name = $argv[1];
$num1 = $argv[2];
$num2 = $argv[3];

$q = "-- Create a table with all connections
create or replace view Connection(A1, A2) as
select distinct F.actor_id, S.actor_id from Acting as F, Acting as S
where F.movie_id = S.movie_id and F.actor_id != S.actor_id;

select * from Connection";

$r = dbQuery($db, mkSQL($q));

$i = 1;
while ($t = dbNext($r)) {
  //if ($t[1] >= $num1 && $t[1] <= $num2) {
    echo "$i. $t[0] ($t[1])\n";
    $i++;
  //}
}

/*

Join two tables (this is a right dictional)

create or replace view Connection(A1, A2) as
select distinct F.actor_id, S.actor_id from Acting as F, Acting as S
where F.movie_id = S.movie_id and F.actor_id != S.actor_id;

Oh my god this is too slow

$q = "with recursive Tree(Actor, Degree) as (
    select (select id from Actor where lower(name) = lower('$name')) as Actor, 0 as Degree -- pass in starting actor id and 0 as the default degree
union all
    select distinct A.actor_id, (T.Degree + 1) as Degree from Acting as A, Tree as T
    where A.actor_id not in (Actor)
    and A.movie_id in (select distinct movie_id from Acting where actor_id in (Actor))
    and T.Degree < $num2
)
select A.name, T.Degree from Tree as T, Actor as A
where T.Actor = A.id order by A.name";
*/

?>
