#!/usr/bin/php
<?php

// include the common PHP code file
require("a2.php");

$usage = "Usage: $argv[0] Name Num1 Num2";
// Init connection with database
$db = dbConnect(DB_CONNECTION);

// Check arguments
if (count($argv) < 3) exit("$usage\n");

$name = $argv[1];
$num1 = $argv[2];
$num2 = $argv[3];

$q = "-- Create a table with all connections
create or replace view Connection(A1, A2) as
select distinct F.actor_id, S.actor_id from Acting as F, Acting as S
where F.movie_id = S.movie_id and F.actor_id != S.actor_id;


-- find all connections recursively
with recursive Tree(A1, A2, Degree) as (
  select A1, A2, 1 as Degree from Connection where A1 = (select id from Actor where lower(name) = lower('$name'))
union all
  select distinct T.A2, C.A2, T.Degree + 1 from Tree as T, Connection as C
  where C.A1 = T.A2 and C.A2 != T.A1 and C.A2 != T.A2 and T.Degree < $num2
)


-- format nicely and remove duplicates (there must be a better way)
select A.name, F.Degree from (select T.A2, min(T.Degree) as Degree from Tree as T group by T.A2) as F, Actor as A
where F.A2 = A.id and F.A2 != (select id from Actor where lower(name) = lower('$name')) and F.Degree >= $num1 and F.Degree <= $num2 order by F.Degree, A.name";

$r = dbQuery($db, mkSQL($q));

$i = 1;
while ($t = dbNext($r)) {
  echo "$i. $t[0] ($t[1])\n";
  $i++;
}
