#!/usr/bin/php
<?php

// include the common PHP code file
require("a2.php");

$usage = "Usage: $argv[0] Title Number";
// Init connection with database
// $db = dbConnect(DB_CONNECTION);

// Check arguments at least 3 can be 4
$arg_count = count($argv);
if ($arg_count < 3) exit("$usage\n");

?>