#!/usr/bin/php
<?php

// include the common PHP code file
require("a2.php");

$usage = "Usage: $argv[0] Title Number";
// Init connection with database
$db = dbConnect(DB_CONNECTION);

// Check arguments at least 2
$arg_count = count($argv);
if ($arg_count < 3) exit("$usage\n");

$name = $argv[1];
$number = $argv[2];
// Check if Number is valid
$valid = false;
if (is_numeric($number) && $number >= 1 && $number <= 1000) $valid = true;
if (!$valid) exit("$usage\n");

// Lots of with...
$q = "with OnlyOne as (select id from Movie where title = 'Happy Feet' order by year desc limit 1),
        OneGenre as (select G.Genre from Genre as G, OnlyOne as O where G.movie_id = O.id),
        OneKeyword as (select K.Keyword from Keyword as K, OnlyOne as O where K.movie_id = O.id),
        AllGenre as (select M.id, count(G.Genre) as \"genre\" from Movie as M, Genre as G 
          where M.id = G.movie_id and G.Genre in (select genre from OneGenre) group by M.id),
        AllKeyword as (select M.id, count(K.Keyword) as \"keyword\" from Movie as M, Keyword as K 
          where M.id = K.movie_id and K.keyword in (select keyword from OneKeyword) group by M.id),
        ExtraInfo as (select M.id, M.title, M.year, R.imdb_score, R.num_voted_users from Movie as M, Rating as R where M.id = R.movie_id)
      select E.title, E.year, G.genre, K.keyword, E.imdb_score, E.num_voted_users
      from ExtraInfo as E, AllGenre as G, AllKeyword as K, OnlyOne as O
      where E.id != O.id and E.id = G.id and E.id = K.id
      order by G.genre desc, K.keyword desc, E.imdb_score desc, E.num_voted_users desc
      limit $number";
$r = dbQuery($db, mkSQL($q));

$i = 1; // Number
while ($t = dbNext($r)) {
  echo "$i. $t[0]";
  if (!empty($t[1]))
    echo " ($t[1])";
  echo " [";
  if (!empty($t[2]))
    echo "$t[2]";
  if (!empty($t[3]))
    echo ", $t[3]";
  if (!empty($t[4]))
    echo ", $t[4]";
  if (!empty($t[5]))
    echo ", $t[5]";
  echo "]\n";
  $i++;
}

?>