#!/usr/bin/php
<?php

// include the common PHP code file
require("a2.php");

$usage = "Usage: $argv[0] Title Number";
// Init connection with database
$db = dbConnect(DB_CONNECTION);

// Check arguments at least 2
$arg_count = count($argv);
if ($arg_count < 3) exit("$usage\n");

$name = $argv[1];
$number = $argv[2];
// Check if Number is valid
$valid = false;
if (is_numeric($number) && $number >= 1 && $number <= 1000) $valid = true;
if (!$valid) exit("$usage\n");

$q = "with OnlyOne as (select id from Movie where title = Happy Feet order by year desc limit 1)
";
$q = "select M.title, D.name, M.year, M.content_rating, R.imdb_score
      from Movie as M, Acting as A, Actor as T, Director as D, Rating as R
      where M.id = A.movie_id and T.id = A.actor_id and lower(T.name) = lower('$value') and M.director_id = D.id and M.id = R.movie_id
      order by M.year, M.title";
$r = dbQuery($db, mkSQL($q));

$i = 1; // Number
while ($t = dbNext($r)) {
  echo "$i. $t[0] -- $t[1] (";
  if (!empty($t[2]))
    echo "$t[2], ";
  if (!empty($t[3]))
    echo "$t[3], ";
  if (!empty($t[4]))
    echo "$t[4]";
  echo ")\n";
  $i++;
}

?>