#!/usr/bin/php
<?php

// include the common PHP code file
require("a2.php");

$usage = "Usage: $argv[0] Title";
// Init connection with database
$db = dbConnect(DB_CONNECTION);

// Check arguments
if (count($argv) < 2) exit("$usage\n");

// Get the return results
$value = $argv[1];

$q = "select M.title, M.year, M.content_rating, R.imdb_score
from Movie as M, Rating as R
where lower(M.title) like lower('\%$value\%') and M.id = R.movie_id
order by M.year, M.title";
$r = dbQuery($db, mkSQL($q, $value));

$i = 1; // Number
while ($t = dbNext($r)) {
  echo "$i. $t[0] (";
  if (!empty($t[1]))
    echo "$t[1], ";
  if (!empty($t[2]))
    echo "$t[2], ";
  if (!empty($t[3]))
    echo "$t[3]";
  echo ")\n";
  $i++;
}

?>