#!/usr/bin/php
<?php

// include the common PHP code file
require("a2.php");

$usage = "Usage: $argv[0] Title";
// Init connection with database
$db = dbConnect(DB_CONNECTION);

// Check arguments
if (count($argv) < 2) exit("$usage\n");

// Get the return results
$value = $argv[1];

$q = "select M.title, M.year, M.content_rating, R.imdb_score, G.genre
from Movie as M, Rating as R, Genre as G
where lower(M.title) like lower('\%$value\%') and M.id = R.movie_id and M.id = G.movie_id
order by M.year, M.title, G.genre";
$r = dbQuery($db, mkSQL($q, $value));

$i = 1; // Number
$curr = ''; // Track movies
while ($t = dbNext($r)) {
  if ($curr != $t[0]) {
    if ($curr != '') {
      // for initial value
      echo "]\n";
    }

    $curr = $t[0];
    echo "$i. $t[0] (";
    if (!empty($t[1]))
      echo "$t[1], ";
    if (!empty($t[2]))
      echo "$t[2], ";
    if (!empty($t[3]))
      echo "$t[3]";
    echo ") [";

    // If no genre, it is just a []
    if (!empty($t[4]))
      echo "$t[4]";
    
    $i++;
  } else {
    if (!empty($t[4]))
      echo ", $t[4]";
    // If curr does not change, do not increase i
  }
}

// In case loop was never entered
if ($curr != '') {
  echo "]\n";
}

?>