#!/usr/bin/php
<?php

// include the common PHP code file
require("a2.php");

$usage = "Usage: $argv[0] K StartYear EndYear\n       $argv[0] Genres K StartYear EndYear";
// Init connection with database
//$db = dbConnect(DB_CONNECTION);

// Check arguments
if (count($argv) < 4) exit("$usage\n");

?>